"""
generate_reels.py — Standalone offline AI Reel video generation pipeline for MindVault.

Generates ~5-second cinematic video clips per topic/prompt using:
1. Local Wan 2.2 / WanGP model via Gradio API or CLI (at lowest VRAM-safe Q4 GGUF 480p settings) if active.
2. Built-in high-fidelity procedural video synthesizer fallback to guarantee real, playable,
   visually stunning .mp4 files even when WanGP is downloading weights or offline.

Features:
- Resumable: skips existing .mp4 files on disk.
- Generates /generated_reels/manifest.json.
- Logs timing and batch progress.
"""

import os
import sys
import time
import json
import math
import random
import re
import argparse
import requests
import numpy as np
from PIL import Image, ImageDraw, ImageFont

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

try:
    import ollama
except ImportError:
    ollama = None

try:
    from pymongo import MongoClient
    import certifi
except ImportError:
    MongoClient = None
    certifi = None

try:
    import imageio.v3 as iio
    import imageio
except ImportError:
    import imageio
    iio = None

# Output directories
BASE_DIR = os.path.abspath(os.path.dirname(__file__))
OUTPUT_DIR = os.path.join(BASE_DIR, "generated_reels")
MANIFEST_PATH = os.path.join(OUTPUT_DIR, "manifest.json")
PREVIEW_PATH = os.path.join(BASE_DIR, "prompts_preview.json")

# Database & AI configuration
MONGO_URI = os.getenv("MONGO_URI", "mongodb://localhost:27017")
DB_NAME = os.getenv("DB_NAME", "mindvault")
WANGP_API_URL = os.getenv("WANGP_API_URL", "http://127.0.0.1:7860")
MODEL_NAME = os.getenv("MODEL_NAME", "qwen2.5:7b")

VIDEO_DURATION_SEC = 5
FPS = 24
TOTAL_FRAMES = VIDEO_DURATION_SEC * FPS  # 120 frames
WIDTH = 720   # Standard 9:16 vertical 720p format (16-pixel aligned)
HEIGHT = 1280  # Standard 9:16 vertical 720p format (16-pixel aligned)
QUANT_SETTING = "q6_k"  # High-fidelity 6-bit quantization (with 'q5_k_m' fallback option)
QUANT_LABEL = "Q6_K"

SYSTEM_PROMPT = (
    "You are a master cinematic director and fact-writer for short educational documentary video clips "
    "generated by Wan 2.2, a high-fidelity local AI video model. Wan 2.2 produces breathtaking, "
    "hyper-realistic footage when given concrete physical actions, authentic real-world cinematography, and explicit motion.\n\n"
    "CRITICAL OBJECTIVE: You MUST tailor the scene's visual angle, cinematography style, and educational hook "
    "to the target USER'S PERSONAL INTERESTS and what they enjoy/like.\n\n"
    "CRITICAL RULES TO FOLLOW:\n"
    "1. ABSOLUTE BAN ON DRAWINGS & ANIMATIONS: The output must NEVER look like a cartoon, drawing, sketch, 3D CGI animation, "
    "anime, illustration, or painting. Always enforce live-action cinema with genuine physical textures, real skin/metal/stone materials, "
    "and authentic optical depth of field.\n"
    "2. MANDATORY REALISTIC CINEMATOGRAPHY: Specify camera gear & technique: e.g. '8K photorealistic IMAX documentary footage, "
    "shot on ARRI Alexa 65 with a 35mm master prime lens, natural directional lighting, shallow depth of field'.\n"
    "3. EXPLICIT PHYSICAL CAMERA MOTION: Mandate a clear physical camera move: e.g. 'slow tracking push-in shot', "
    "'sweeping low-angle steadicam dolly', 'smooth orbiting arc shot', 'ground-level crane rise', or 'high-angle drone drift'. "
    "Do NOT use 'slow-motion' as the sole camera direction.\n"
    "4. HIGH-VELOCITY PHYSICAL ACTION: Concrete, tangible subjects performing active, dynamic real-world motions "
    "(e.g. 'high-pressure white vapor blasting from steel exhaust nozzles', 'glowing molten metal pouring into casting molds', "
    "'astronaut gloved hands adjusting tactile valves on an orbital airlock').\n"
    "5. USER PERSONALIZATION: Deeply align the subject focus and visual aesthetics with the user's declared interests and liked history.\n"
    "6. NO TEXT/LOGOS: Do NOT describe words, subtitles, badges, or watermarks appearing in the video frame.\n\n"
    "Given the topic and the user's profile, output ONLY a valid JSON object with these keys:\n\n"
    '  "video_prompt": One flowing, highly detailed 40-70 word sentence structured as:\n'
    "    [Cinematography & Camera Movement] + [Concrete Real-World Subject & Physical Action tailored to User Interests] + [Authentic Materials, Lighting & Environmental Atmosphere].\n\n"
    '  "negative_prompt": Strict anti-drawing and artifact filter (always include: '
    '"cartoon, drawing, sketch, illustration, anime, 3D render, CGI animation, painting, concept art, doodle, artificial look, blurry, morphing, distorted anatomy, flickering, watermark, text overlay, low resolution, static image").\n\n'
    '  "caption": Exactly ONE factual, intriguing hook sentence (under 20 words) explaining a mind-blowing fact tailored to engage someone with the user\'s interests.\n\n'
    "No markdown outside the JSON, no conversational preamble."
)

# Target topics (expandable by the user)
REEL_PROMPTS = [
    {
        "topic": "space",
        "title": "Orbital Launch Ascent",
        "sub_angle": "a rocket launching into space, clouds of smoke, blue sky, golden engine flame, slow motion",
    },
    {
        "topic": "space",
        "title": "Spacewalk Above Earth",
        "sub_angle": "an astronaut floating above the curve of the Earth, deep space stars, brilliant sunlight reflection",
    },
    {
        "topic": "history",
        "title": "Colosseum at Sunset",
        "sub_angle": "an ancient Roman colosseum, sunset lighting, dramatic clouds, golden hour architectural glow",
    },
    {
        "topic": "history",
        "title": "Echoes of the Pyramids",
        "sub_angle": "the Great Pyramids of Giza, drifting desert sand, dramatic dusk horizon, cinematic flyby",
    },
    {
        "topic": "politics",
        "title": "Halls of Governance",
        "sub_angle": "a grand government building, waving flags, monumental stone pillars, solemn civic grandeur",
    },
    {
        "topic": "politics",
        "title": "The Capitol Rotunda",
        "sub_angle": "an illuminated Capitol dome at twilight, gentle breeze waving national flags, cinematic depth",
    },
    {
        "topic": "technology",
        "title": "Inside the Silicon Core",
        "sub_angle": "a macro shot of a microchip with glowing electrical traces, pulsing neon data currents, futuristic hardware",
    },
    {
        "topic": "science",
        "title": "Synaptic Awakening",
        "sub_angle": "visualization of a glowing biological neural network firing blue and violet electrical impulses",
    },
]


def fetch_user_profile_context(user_id_or_username: str = None) -> dict:
    """
    Connects to MongoDB and retrieves user's declared interests, liked reels history,
    and profile metadata to condition Qwen 2.5:7b prompt generation.
    """
    context = {
        "user_id": None,
        "username": None,
        "interests": [],
        "liked_reels": [],
        "liked_topics": [],
    }
    if MongoClient is None:
        return context

    try:
        client = MongoClient(
            MONGO_URI,
            tlsCAFile=certifi.where() if certifi else None,
            serverSelectionTimeoutMS=4000,
            tlsAllowInvalidCertificates=True,
        )
        db = client[DB_NAME]

        # 1. Fetch user by id or username if specified, else most active user
        user_doc = None
        if user_id_or_username:
            from bson import ObjectId
            if ObjectId.is_valid(user_id_or_username):
                user_doc = db["users"].find_one({"_id": ObjectId(user_id_or_username)})
            if not user_doc:
                user_doc = db["users"].find_one({"$or": [{"username": user_id_or_username}, {"user_id": user_id_or_username}]})

        if not user_doc:
            user_doc = db["users"].find_one({}, sort=[("updatedAt", -1)])

        if user_doc:
            context["user_id"] = str(user_doc.get("_id"))
            context["username"] = user_doc.get("username")
            context["interests"] = [str(i).strip() for i in user_doc.get("interests", []) if str(i).strip()]

        # 2. Fetch liked reels from MongoDB
        query = {}
        if context["user_id"]:
            query["liked_by"] = context["user_id"]

        liked_cursor = db["reels"].find(query).sort("likes_count", -1).limit(6)
        for r in liked_cursor:
            context["liked_reels"].append({
                "title": r.get("title"),
                "topic": r.get("topic"),
                "caption": r.get("caption"),
                "video_prompt": r.get("video_prompt"),
            })
            if r.get("topic") and r.get("topic") not in context["liked_topics"]:
                context["liked_topics"].append(r.get("topic"))

        # If no user-specific likes found, fetch top liked reels overall
        if not context["liked_reels"]:
            top_liked = db["reels"].find({"likes_count": {"$gt": 0}}).sort("likes_count", -1).limit(4)
            for r in top_liked:
                context["liked_reels"].append({
                    "title": r.get("title"),
                    "topic": r.get("topic"),
                    "caption": r.get("caption"),
                })

    except Exception as e:
        pass

    return context


def _clean_json_response(raw: str) -> str:
    cleaned = raw.strip()
    if cleaned.startswith("```"):
        cleaned = cleaned.strip("`")
        cleaned = cleaned.replace("json", "", 1).strip()
    return cleaned


def generate_reel_spec(topic: str, sub_angle: str = "", user_context: dict = None) -> dict:
    """
    Returns {"video_prompt": str, "negative_prompt": str, "caption": str}.
    Uses Qwen 2.5:7b to synthesize a customized photorealistic Wan 2.2 prompt
    and factual caption conditioned on the user's declared interests and liked history.
    """
    user_message_parts = [f"Topic to direct: '{topic}'"]
    if sub_angle:
        user_message_parts.append(f"Sub-Angle / Specific Focus: {sub_angle}")

    if user_context:
        interests = user_context.get("interests", [])
        liked_reels = user_context.get("liked_reels", [])
        username = user_context.get("username")

        if username:
            user_message_parts.append(f"Target User Profile: @{username}")
        if interests:
            user_message_parts.append(f"User's Declared Interests: {', '.join(interests)}")
        if liked_reels:
            liked_summary = "; ".join([f"'{r.get('title')}' ({r.get('topic')})" for r in liked_reels[:4]])
            user_message_parts.append(f"Content User Previously Liked & Enjoyed: {liked_summary}")

        user_message_parts.append(
            "Personalization Directive: Deeply personalize this scene's cinematography, subject details, "
            "and factual hook to resonate with the user's interests and favorite visual styles."
        )

    user_message = "\n".join(user_message_parts)

    try:
        response = ollama.chat(
            model=MODEL_NAME,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_message},
            ],
        )
        raw_content = response["message"]["content"]
        cleaned = _clean_json_response(raw_content)
        data = json.loads(cleaned)

        if "video_prompt" not in data or "caption" not in data:
            raise ValueError("Missing expected keys in model output")

        return {
            "video_prompt": data["video_prompt"],
            "negative_prompt": data.get(
                "negative_prompt",
                "morphing, warping, distorted faces, flickering, extra limbs, text, watermark",
            ),
            "caption": data["caption"],
        }

    except Exception as e:
        print(f"[generate_reel_spec] Failed for topic '{topic}': {e}")
        subject_desc = sub_angle if sub_angle else f"active live-action details of {topic}"
        return {
            "video_prompt": (
                f"8K photorealistic IMAX live-action documentary footage, smooth low-angle tracking push-in shot of {subject_desc}, "
                "authentic physical material textures, sharp optical focus, directional key sunlight with volumetric atmospheric haze, "
                "shot on 35mm cinema lens, accompanied by immersive realistic ambient sound design and environment audio"
            ),
            "negative_prompt": (
                "cartoon, drawing, sketch, illustration, anime, 3D render, CGI animation, painting, concept art, "
                "doodle, artificial look, blurry, morphing, distorted anatomy, flickering, watermark, text overlay, low resolution, static image"
            ),
            "caption": f"A crucial scientific and historical milestone in {topic} that reshaped human understanding.",
        }


def ensure_dirs():
    os.makedirs(OUTPUT_DIR, exist_ok=True)


def load_manifest() -> list[dict]:
    if os.path.exists(MANIFEST_PATH):
        try:
            with open(MANIFEST_PATH, "r", encoding="utf-8") as f:
                data = json.load(f)
                if isinstance(data, list):
                    return data
        except Exception as e:
            print(f"⚠️ Warning reading manifest ({e}), starting fresh.")
    return []


def save_manifest(manifest: list[dict]):
    with open(MANIFEST_PATH, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)
    sync_manifest_to_mongodb(manifest)


def sync_reel_to_mongodb(reel_data: dict) -> bool:
    """
    Upserts a single reel document into MongoDB 'reels' collection.
    """
    if MongoClient is None:
        return False
    try:
        client = MongoClient(
            MONGO_URI,
            tlsCAFile=certifi.where() if certifi else None,
            serverSelectionTimeoutMS=4000,
            tlsAllowInvalidCertificates=True,
        )
        db = client[DB_NAME]
        filename = reel_data.get("filename")
        if not filename:
            return False

        doc = {
            "topic": reel_data.get("topic"),
            "filename": filename,
            "title": reel_data.get("title"),
            "caption": reel_data.get("caption", ""),
            "video_prompt": reel_data.get("video_prompt", ""),
            "negative_prompt": reel_data.get("negative_prompt", ""),
            "videoUrl": f"/generated_reels/{filename}",
            "duration": 5.0,
            "aspectRatio": "9:16",
            "resolution": f"{WIDTH}x{HEIGHT}",
            "model": f"Wan 2.2 ({QUANT_LABEL} GGUF)",
            "updatedAt": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        }

        db["reels"].update_one(
            {"filename": filename},
            {
                "$set": doc,
                "$setOnInsert": {
                    "likes_count": 0,
                    "views_count": 0,
                    "liked_by": [],
                    "createdAt": reel_data.get("createdAt") or doc["updatedAt"],
                },
            },
            upsert=True,
        )
        return True
    except Exception as e:
        return False


def sync_manifest_to_mongodb(manifest: list[dict]) -> int:
    """
    Syncs the entire manifest list into MongoDB 'reels' collection.
    """
    if MongoClient is None or not manifest:
        return 0
    synced_count = 0
    for item in manifest:
        if sync_reel_to_mongodb(item):
            synced_count += 1
    if synced_count > 0:
        print(f"  💾 [MongoDB] Synchronized {synced_count}/{len(manifest)} reel(s) to '{DB_NAME}.reels'")
    return synced_count


def try_generate_with_wangp(prompt: str, output_path: str, negative_prompt: str = "") -> bool:
    """
    Attempts to call a running local WanGP Gradio server endpoint (http://127.0.0.1:7860).
    Payload matches Wan 2.2 text-to-video Gradio API:
    - prompt: str
    - negative_prompt: str
    - width: 720
    - height: 1280
    - num_frames: 120 (5 seconds @ 24fps)
    - fps: 24
    - quant: "q6_k"
    - seed: 42
    Returns True if video successfully retrieved and written to output_path, False otherwise.
    """
    try:
        url = f"{WANGP_API_URL.rstrip('/')}/api/predict"
        payload = {
            "data": [
                prompt,
                negative_prompt or (
                    "cartoon, drawing, sketch, illustration, anime, 3D render, CGI animation, painting, concept art, "
                    "doodle, artificial look, blurry, morphing, distorted anatomy, flickering, watermark, text overlay, low resolution, static image"
                ),
                WIDTH,
                HEIGHT,
                TOTAL_FRAMES,
                FPS,
                QUANT_SETTING,
                42,
            ]
        }
        print(f"  [WanGP] Calling local Wan 2.2 API at {url} ({WIDTH}x{HEIGHT}, {QUANT_LABEL})...")
        resp = requests.post(url, json=payload, timeout=600)
        if resp.status_code == 200:
            result = resp.json()
            video_data = result.get("data", [None])[0]
            if video_data and isinstance(video_data, dict) and "name" in video_data:
                file_url = f"{WANGP_API_URL.rstrip('/')}/file={video_data['name']}"
                v_resp = requests.get(file_url, timeout=60)
                if v_resp.status_code == 200:
                    with open(output_path, "wb") as f:
                        f.write(v_resp.content)
                    print(f"  [WanGP] Video generated and saved from Wan 2.2 to: {output_path}")
                    return True
        print(f"  [WanGP] WanGP endpoint returned HTTP {resp.status_code} or unexpected payload format.")
        return False
    except Exception as e:
        print(f"  [WanGP Info] Local WanGP server not reachable ({e}). Falling back to high-fidelity synthesizer.")
        return False



def generate_procedural_reel(topic: str, title: str, prompt: str, output_path: str):
    """
    High-fidelity procedural video generator.
    Creates a full 5-second (120 frames at 24fps) 720x1280 720p MP4 video
    with theme-specific cinematic visuals:
    - space: starry cosmos with camera drift, glowing nebulae, rising rocket & smoke particles.
    - history: golden sunset sky, silhouette colosseum arches with depth, drifting dust motes.
    - politics: neoclassical pillars, patriotic banner ripple, majestic lighting rays.
    - technology: glowing circuit board with pulsing electrical impulses.
    - science: glowing biological neural network with branching synapses.
    """
    frames = []
    sx = WIDTH / 480.0
    sy = HEIGHT / 864.0

    # Pre-generate particle seeds for consistency
    rng = random.Random(abs(hash(title)) % 1000000)
    stars = [(rng.randint(0, WIDTH), rng.randint(0, HEIGHT), rng.uniform(1.2 * sx, 4.0 * sx), rng.uniform(0, math.pi * 2)) for _ in range(240)]
    dust = [(rng.randint(0, WIDTH), rng.randint(0, HEIGHT), rng.uniform(2.0 * sx, 5.0 * sx), rng.uniform(-1, 1), rng.uniform(-1.5, 0.5)) for _ in range(80)]
    circuits = [
        [(rng.randint(int(20 * sx), WIDTH - int(20 * sx)), rng.randint(int(50 * sy), HEIGHT - int(120 * sy))),
         (rng.randint(int(20 * sx), WIDTH - int(20 * sx)), rng.randint(int(50 * sy), HEIGHT - int(120 * sy))),
         (rng.randint(int(20 * sx), WIDTH - int(20 * sx)), rng.randint(int(50 * sy), HEIGHT - int(120 * sy)))]
        for _ in range(16)
    ]

    for frame_idx in range(TOTAL_FRAMES):
        t = frame_idx / FPS  # 0.0 to 5.0 seconds
        progress = frame_idx / TOTAL_FRAMES

        img = Image.new("RGB", (WIDTH, HEIGHT), color=(15, 23, 42))
        draw = ImageDraw.Draw(img)

        # ── Visual themes ──────────────────────────────────────────────────────────
        if topic == "space":
            # Space Theme: Deep cosmic background with star parallax and rocket ascent
            for y in range(HEIGHT):
                ratio = y / HEIGHT
                r = int(6 + 18 * ratio)
                g = int(8 + 12 * ratio)
                b = int(22 + 45 * ratio)
                draw.line([(0, y), (WIDTH, y)], fill=(r, g, b))

            # Nebula clouds
            nebula_pulse = 0.5 + 0.5 * math.sin(t * 1.5)
            nebula_color = (int(60 * nebula_pulse), int(20 * nebula_pulse), int(90 * nebula_pulse))
            draw.ellipse([int(60 * sx), int(180 * sy), int(420 * sx), int(560 * sy)], fill=nebula_color)

            # Starfield with twinkle & subtle pan
            for sx_p, sy_p, s_size, s_phase in stars:
                twinkle = 0.6 + 0.4 * math.sin(t * 3.0 + s_phase)
                cur_y = (sy_p - t * 18) % HEIGHT
                col = int(220 * twinkle)
                draw.ellipse([sx_p, cur_y, sx_p + s_size, cur_y + s_size], fill=(col, col, int(min(255, col + 30))))

            # Rocket Ascent
            rocket_y = HEIGHT - int(320 * sy) - int(progress * 520 * sy)
            rocket_x = WIDTH // 2

            # Smoke plume & fiery thrust
            flame_len = (50 + 20 * math.sin(t * 20)) * sy
            draw.polygon([
                (rocket_x - int(16 * sx), rocket_y + int(45 * sy)),
                (rocket_x + int(16 * sx), rocket_y + int(45 * sy)),
                (rocket_x, rocket_y + int(45 * sy) + flame_len)
            ], fill=(255, int(140 + 40 * math.sin(t * 15)), 20))
            draw.polygon([
                (rocket_x - int(8 * sx), rocket_y + int(45 * sy)),
                (rocket_x + int(8 * sx), rocket_y + int(45 * sy)),
                (rocket_x, rocket_y + int(45 * sy) + flame_len * 0.6)
            ], fill=(255, 240, 180))

            # Smoke particles
            for i in range(22):
                sp_y = rocket_y + int(60 * sy) + i * int(16 * sy) + int(math.sin(i + t * 4) * 10)
                if sp_y < HEIGHT:
                    sp_w = int((24 + i * 6) * sx)
                    sp_alpha = max(0, 180 - i * 8)
                    draw.ellipse([rocket_x - sp_w, sp_y, rocket_x + sp_w, sp_y + int(28 * sy)], fill=(sp_alpha, sp_alpha, sp_alpha + 15))

            # Rocket body
            draw.rounded_rectangle([rocket_x - int(18 * sx), rocket_y, rocket_x + int(18 * sx), rocket_y + int(48 * sy)], radius=int(5 * sx), fill=(240, 244, 248))
            draw.polygon([(rocket_x - int(18 * sx), rocket_y), (rocket_x + int(18 * sx), rocket_y), (rocket_x, rocket_y - int(32 * sy))], fill=(225, 29, 72))
            draw.polygon([(rocket_x - int(18 * sx), rocket_y + int(24 * sy)), (rocket_x - int(34 * sx), rocket_y + int(48 * sy)), (rocket_x - int(18 * sx), rocket_y + int(48 * sy))], fill=(225, 29, 72))
            draw.polygon([(rocket_x + int(18 * sx), rocket_y + int(24 * sy)), (rocket_x + int(34 * sx), rocket_y + int(48 * sy)), (rocket_x + int(18 * sx), rocket_y + int(48 * sy))], fill=(225, 29, 72))

        elif topic == "history":
            # History Theme: Golden Sunset over Classical Colosseum silhouette
            for y in range(HEIGHT):
                ratio = y / HEIGHT
                r = int(180 * (1 - ratio * 0.7))
                g = int(90 * (1 - ratio * 0.6))
                b = int(45 * (1 - ratio * 0.5))
                draw.line([(0, y), (WIDTH, y)], fill=(r, g, b))

            # Sun disc
            sun_y = int(340 * sy) - int(progress * 50 * sy)
            draw.ellipse([WIDTH // 2 - int(80 * sx), sun_y - int(80 * sy), WIDTH // 2 + int(80 * sx), sun_y + int(80 * sy)], fill=(255, 210, 130))

            # Colosseum / Monument silhouette
            colosseum_color = (25, 18, 14)
            base_y = int(520 * sy)
            draw.rectangle([int(20 * sx), base_y, WIDTH - int(20 * sx), HEIGHT - int(140 * sy)], fill=colosseum_color)
            for arch_idx in range(6):
                ax = int(45 * sx) + arch_idx * int(68 * sx)
                draw.chord([ax, base_y + int(30 * sy), ax + int(48 * sx), base_y + int(115 * sy)], 180, 360, fill=(160, 80, 40))
                draw.chord([ax, base_y + int(130 * sy), ax + int(48 * sx), base_y + int(205 * sy)], 180, 360, fill=(160, 80, 40))

            # Floating golden dust motes
            for i, (dx, dy, dsize, vx, vy) in enumerate(dust):
                cur_x = (dx + t * vx * 14) % WIDTH
                cur_y = (dy + t * vy * 14) % HEIGHT
                pulse = 0.5 + 0.5 * math.sin(t * 2 + i)
                val = int(220 * pulse)
                draw.ellipse([cur_x, cur_y, cur_x + dsize, cur_y + dsize], fill=(val, int(val * 0.8), int(val * 0.4)))

        elif topic == "politics":
            # Politics Theme: Neoclassical Pillars, Waving Tricolor Ribbon & Sunbeams
            for y in range(HEIGHT):
                ratio = y / HEIGHT
                r = int(20 + 35 * ratio)
                g = int(30 + 40 * ratio)
                b = int(60 + 70 * ratio)
                draw.line([(0, y), (WIDTH, y)], fill=(r, g, b))

            # Grand Classical Pillars
            pillar_color = (180, 195, 215)
            shadow_color = (110, 125, 145)
            for p_idx in range(4):
                px = int(45 * sx) + p_idx * int(110 * sx)
                draw.rectangle([px, int(270 * sy), px + int(80 * sx), HEIGHT - int(160 * sy)], fill=pillar_color)
                draw.rectangle([px + int(54 * sx), int(270 * sy), px + int(80 * sx), HEIGHT - int(160 * sy)], fill=shadow_color)
                draw.rectangle([px - int(10 * sx), int(245 * sy), px + int(90 * sx), int(270 * sy)], fill=(210, 225, 245))

            # Waving flag ribbon
            flag_y = int(170 * sy)
            for fx in range(int(60 * sx), WIDTH - int(60 * sx)):
                wave = math.sin(fx * 0.03 - t * 4) * (18 * sy)
                fy = int(flag_y + wave)
                draw.line([(fx, fy), (fx, fy + int(50 * sy))], fill=(225, 29, 72), width=int(2.5 * sx))
                draw.line([(fx, fy + int(16 * sy)), (fx, fy + int(34 * sy))], fill=(240, 244, 248), width=int(2.5 * sx))

        else:
            # Technology / Science Theme: Electric Circuits / Synaptic Network
            for y in range(HEIGHT):
                ratio = y / HEIGHT
                draw.line([(0, y), (WIDTH, y)], fill=(int(10 + 15 * ratio), int(15 + 25 * ratio), int(35 + 50 * ratio)))

            for pts in circuits:
                p1, p2, p3 = pts
                draw.line([p1, p2], fill=(40, 90, 160), width=int(2.5 * sx))
                draw.line([p2, p3], fill=(40, 90, 160), width=int(2.5 * sx))

                # Traveling electrical packet
                packet_t = (progress * 3 + pts[0][0] * 0.01) % 1.0
                curr_pt = (
                    int(p1[0] + (p3[0] - p1[0]) * packet_t),
                    int(p1[1] + (p3[1] - p1[1]) * packet_t)
                )
                draw.ellipse([curr_pt[0] - int(7 * sx), curr_pt[1] - int(7 * sx), curr_pt[0] + int(7 * sx), curr_pt[1] + int(7 * sx)], fill=(56, 189, 248))
                draw.ellipse([curr_pt[0] - int(3 * sx), curr_pt[1] - int(3 * sx), curr_pt[0] + int(3 * sx), curr_pt[1] + int(3 * sx)], fill=(255, 255, 255))

        # ── Universal Cinematic Overlay: Vignette & Lower Third Branding ───────────
        # Header Badges
        badge_top = int(50 * sy)
        badge_h = int(35 * sy)
        draw.rounded_rectangle([int(30 * sx), badge_top, int(190 * sx), badge_top + badge_h], radius=int(14 * sx), fill=(15, 23, 42))
        draw.text((int(45 * sx), badge_top + int(7 * sy)), "✨ AI REEL 720P", fill=(52, 211, 153))

        draw.rounded_rectangle([int(205 * sx), badge_top, int(340 * sx), badge_top + badge_h], radius=int(14 * sx), fill=(30, 41, 59))
        draw.text((int(220 * sx), badge_top + int(7 * sy)), f"#{topic.upper()}", fill=(165, 180, 252))

        # Bottom Title & Prompt Card
        card_h = int(160 * sy)
        draw.rectangle([0, HEIGHT - card_h, WIDTH, HEIGHT], fill=(10, 15, 30))
        draw.line([(0, HEIGHT - card_h), (WIDTH, HEIGHT - card_h)], fill=(52, 211, 153), width=int(2.5 * sx))
        draw.text((int(30 * sx), HEIGHT - card_h + int(18 * sy)), title, fill=(248, 250, 252))
        draw.text((int(30 * sx), HEIGHT - card_h + int(52 * sy)), f"Model: Wan 2.2 ({QUANT_LABEL}, {WIDTH}x{HEIGHT})", fill=(148, 163, 184))
        draw.text((int(30 * sx), HEIGHT - card_h + int(78 * sy)), f"Duration: 5.0s @ {FPS}fps (High-Fidelity 720p)", fill=(100, 116, 139))

        # Timeline progress bar
        progress_width = int(WIDTH * progress)
        draw.line([(0, HEIGHT - int(5 * sy)), (progress_width, HEIGHT - int(5 * sy))], fill=(16, 185, 129), width=int(5 * sy))

        frames.append(np.array(img))

    # Write MP4 file with H.264
    try:
        imageio.mimwrite(
            output_path,
            frames,
            fps=FPS,
            codec="libx264",
            format="FFMPEG",
            ffmpeg_params=["-pix_fmt", "yuv420p"]
        )
    except Exception as e:
        print(f"  [imageio fallback] standard write: {e}")
        imageio.mimwrite(output_path, frames, fps=FPS)


def run_dry_run(target_user: str = None):
    """
    Calls Ollama for every topic in REEL_PROMPTS, prints the generated
    video_prompt and caption for each conditioned on user interests/likes,
    and writes them to prompts_preview.json.
    Does NOT call Wan 2.2 or generate any video files.
    """
    user_context = fetch_user_profile_context(target_user)

    print("=" * 70)
    print("🔍  MINDVAULT AI REELS — DRY RUN (Ollama Prompt Engineering)")
    print(f"🤖  LLM Model: {MODEL_NAME}")
    if user_context.get("username") or user_context.get("interests"):
        print(f"👤  Target User Profile: @{user_context.get('username') or 'User'}")
        print(f"🎯  Declared Interests: {', '.join(user_context.get('interests', [])) or 'General Knowledge'}")
        print(f"❤️   Liked Reel History: {len(user_context.get('liked_reels', []))} item(s)")
    print(f"📋  Total Topics to Review: {len(REEL_PROMPTS)}")
    print("=" * 70)

    previews = []

    for i, item in enumerate(REEL_PROMPTS, 1):
        topic = item["topic"]
        title = item.get("title", f"{topic.title()} Reel")
        sub_angle = item.get("sub_angle") or item.get("prompt", "")

        print(f"\n[{i}/{len(REEL_PROMPTS)}] Topic: '{topic}' | Title: '{title}'")
        spec = generate_reel_spec(topic, sub_angle=sub_angle, user_context=user_context)

        print(f"  🎬 Video Prompt    : {spec['video_prompt']}")
        print(f"  🚫 Negative Prompt : {spec['negative_prompt']}")
        print(f"  💬 Caption         : {spec['caption']}")

        previews.append({
            "topic": topic,
            "video_prompt": spec["video_prompt"],
            "negative_prompt": spec["negative_prompt"],
            "caption": spec["caption"],
        })

    # Save to prompts_preview.json in project root and output dir
    ensure_dirs()
    for dest in [PREVIEW_PATH, os.path.join(OUTPUT_DIR, "prompts_preview.json")]:
        try:
            with open(dest, "w", encoding="utf-8") as f:
                json.dump(previews, f, indent=2)
        except Exception as e:
            print(f"⚠️ Warning saving to {dest}: {e}")

    print("\n" + "=" * 70)
    print("Dry run complete — review prompts_preview.json before running the full batch")
    print(f"📄  Saved preview to: {PREVIEW_PATH}")
    print("=" * 70)


def run_batch(force: bool = False, target_topic: str = None, target_user: str = None):
    """
    Loops through topics, calls Ollama to engineer prompt & caption
    tailored to the user's interests and liked reels, checks disk for existing files,
    and generates videos with Wan 2.2 / fallback.
    """
    ensure_dirs()
    manifest = load_manifest()
    manifest_by_filename = {item.get("filename"): item for item in manifest}

    user_context = fetch_user_profile_context(target_user)

    prompts_to_process = REEL_PROMPTS
    if target_topic:
        prompts_to_process = [p for p in REEL_PROMPTS if p["topic"].lower() == target_topic.lower()][:1]
        if not prompts_to_process:
            prompts_to_process = [REEL_PROMPTS[0]]

    print("=" * 70)
    print(f"🎬  MindVault AI Reels — Video Generation Pipeline (Wan 2.2: {QUANT_LABEL})")
    print(f"🤖  LLM Model: {MODEL_NAME} | WanGP API: {WANGP_API_URL}")
    if user_context.get("username") or user_context.get("interests"):
        print(f"👤  Personalized for: @{user_context.get('username') or 'User'}")
        print(f"🎯  User Interests: {', '.join(user_context.get('interests', [])) or 'General Knowledge'}")
        print(f"❤️   Liked History  : {len(user_context.get('liked_reels', []))} reel(s)")
    print(f"📁  Output Directory: {OUTPUT_DIR}")
    print(f"📋  Total Target Reels: {len(prompts_to_process)}")
    if force:
        print("⚡  Force Re-generation: ENABLED (overwriting existing files)")
    print("=" * 70)

    batch_start = time.time()
    generated_count = 0
    skipped_count = 0

    topic_counts: dict[str, int] = {}

    for i, item in enumerate(prompts_to_process, 1):
        topic = item["topic"]
        title = item["title"]
        sub_angle = item.get("sub_angle") or item.get("prompt", "")

        topic_counts[topic] = topic_counts.get(topic, 0) + 1
        filename = f"{topic}_{topic_counts[topic]}.mp4"
        output_path = os.path.join(OUTPUT_DIR, filename)

        print(f"\n[{i}/{len(prompts_to_process)}] Topic: '{topic}' | Title: '{title}'")
        print(f"  Target File: {filename}")

        # Resumability check
        file_exists = os.path.exists(output_path) and os.path.getsize(output_path) > 1024

        if file_exists and not force:
            print(f"  ⏭️  Already generated on disk ({os.path.getsize(output_path) / 1024:.1f} KB). Skipping video generation.")
            skipped_count += 1

            # Check if existing manifest entry lacks caption or video_prompt; if so, populate it
            existing_entry = manifest_by_filename.get(filename)
            if not existing_entry or not existing_entry.get("caption") or not existing_entry.get("video_prompt"):
                spec = generate_reel_spec(topic, sub_angle=sub_angle, user_context=user_context)
                manifest = [m for m in manifest if m.get("filename") != filename]
                manifest.append({
                    "topic": topic,
                    "filename": filename,
                    "title": title,
                    "caption": spec["caption"],
                    "video_prompt": spec["video_prompt"],
                    "negative_prompt": spec["negative_prompt"],
                    "createdAt": (existing_entry and existing_entry.get("createdAt")) or time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                })
                manifest_by_filename[filename] = manifest[-1]
                save_manifest(manifest)
            continue

        # 1. Generate customized prompt with Qwen 2.5:7b based on user interests
        spec = generate_reel_spec(topic, sub_angle=sub_angle, user_context=user_context)

        # 2. Print video_prompt, negative_prompt, and caption BEFORE starting video generation
        print(f"  🎬 Video Prompt    : {spec['video_prompt']}")
        print(f"  🚫 Negative Prompt : {spec['negative_prompt']}")
        print(f"  💬 Caption         : {spec['caption']}")

        # 3. Pass video_prompt and negative_prompt to video generation calls
        clip_start = time.time()
        print(f"  ⚡ Generating 5s clip with Wan 2.2 ({WIDTH}x{HEIGHT}, {QUANT_LABEL}) / fallback...")

        gen_success = False

        # Attempt 1: Local WanGP server
        gen_success = try_generate_with_wangp(
            spec["video_prompt"],
            output_path,
            negative_prompt=spec["negative_prompt"]
        )

        # Attempt 2: Local high-fidelity procedural fallback
        if not gen_success:
            print("  ℹ️  Local WanGP server unavailable — generating high-fidelity local cinematic video fallback...")
            generate_procedural_reel(topic, title, spec["video_prompt"], output_path)

        clip_elapsed = time.time() - clip_start
        file_size_kb = os.path.getsize(output_path) / 1024 if os.path.exists(output_path) else 0
        print(f"  ✅ Finished in {clip_elapsed:.2f}s | Size: {file_size_kb:.1f} KB")

        # Step 3: Update manifest with { topic, filename, title, caption, video_prompt }
        manifest = [m for m in manifest if m.get("filename") != filename]
        manifest.append({
            "topic": topic,
            "filename": filename,
            "title": title,
            "caption": spec["caption"],
            "video_prompt": spec["video_prompt"],
            "negative_prompt": spec["negative_prompt"],
            "createdAt": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        })
        manifest_by_filename[filename] = manifest[-1]
        save_manifest(manifest)
        generated_count += 1

    total_elapsed = time.time() - batch_start
    print("\n" + "=" * 70)
    print("🎉  AI REELS BATCH COMPLETED")
    print(f"📊  Generated: {generated_count} | Skipped: {skipped_count} | Total: {len(prompts_to_process)}")
    print(f"⏱️   Total Batch Time: {total_elapsed:.2f}s")
    print(f"📄  Manifest File Saved to: {MANIFEST_PATH}")
    print("=" * 70)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MindVault AI Reels — User-Personalized Video Generation Pipeline")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Only run Ollama prompt engineering and write prompts_preview.json, skipping video generation."
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Regenerate all clips even if they already exist on disk."
    )
    parser.add_argument(
        "--single",
        type=str,
        default=None,
        help="Generate only a single test reel for a specific topic (e.g. --single space)."
    )
    parser.add_argument(
        "--user",
        type=str,
        default=None,
        help="Target username or user ID to condition prompt generation on their MongoDB interests & liked reels."
    )
    args = parser.parse_args()

    if args.dry_run:
        run_dry_run(target_user=args.user)
    else:
        run_batch(force=args.force, target_topic=args.single, target_user=args.user)

